- algorithm/Algorithm/Algorithm.csproj
- algorithm/Algorithm/Algorithm.sln
- algorithm/Algorithm/Algorithm/Algorithm.cs
- algorithm/Algorithm/Algorithm/Rules/Rule.cs
- algorithm/Algorithm/Algorithm/Rules/VoiceDistance.cs
- algorithm/Algorithm/Communication/FunctionParser.cs
- algorithm/Algorithm/Communication/SymbolParser.cs
- algorithm/Algorithm/Communication/TaskParser.cs
- algorithm/Algorithm/MIDI/MidiNote.cs
- algorithm/Algorithm/MIDI/MidiParser.cs
- algorithm/Algorithm/Music/Alteration.cs
- algorithm/Algorithm/Music/Bar.cs
- algorithm/Algorithm/Music/Chord.cs
- algorithm/Algorithm/Music/Ellipse.cs
- algorithm/Algorithm/Music/Function.cs
- algorithm/Algorithm/Music/FunctionComponent.cs
- algorithm/Algorithm/Music/FunctionType.cs
- algorithm/Algorithm/Music/Interval.cs
- algorithm/Algorithm/Music/Meter.cs
- algorithm/Algorithm/Music/Mode.cs
- algorithm/Algorithm/Music/Note.cs
- algorithm/Algorithm/Music/RhytmicValue.cs
- algorithm/Algorithm/Music/Scale.cs
- algorithm/Algorithm/Music/SecondaryPassage.cs
- algorithm/Algorithm/Music/Symbol.cs
- algorithm/Algorithm/Music/Task.cs
- algorithm/Algorithm/Music/Tonation.cs
Core functionalities of Algorithm.
> Algorithm - core

- algorithm/Algorithm/Algorithm/Rules/FifthOnStrongBar.cs
- algorithm/Algorithm/Algorithm/Rules/ParallelFifths.cs
- algorithm/Algorithm/Algorithm/Rules/ParallelOctaves.cs
- algorithm/Algorithm/Algorithm/Rules/Rule.cs
- algorithm/Algorithm/Algorithm/Rules/SameDirection.cs
- algorithm/Algorithm/Algorithm/Rules/VoiceCrossing.cs
- algorithm/Algorithm/Algorithm/Rules/VoiceDistance.cs
- algorithm/Algorithm/Algorithm/Stack.cs
- algorithm/Algorithm/Algorithm/TaskCheck.cs
- algorithm/Algorithm/Algorithm/UserBar.cs
- algorithm/Algorithm/Algorithm/UserStack.cs
- algorithm/Algorithm/Communication/NoteParser.cs
- algorithm/Algorithm/Communication/TaskBuilder.cs
- algorithm/Algorithm/Communication/TaskParser.cs
- algorithm/Algorithm/Communication/TaskSolver.cs
- algorithm/Algorithm/Music/Tonation.cs
- algorithm/AlgorithmTests/TaskParserTests.cs
Pull request wprowadza w pełni działające parsowanie nut oraz całych zadań, spójnych z formatem JSON ustalonych z @kubawen10.
- Serializacja i deserializacja zadań
- Serializacja i deserializacja nut
- **Zasady bez implementacji** - czyli goła struktura, na ten moment nic ciekawego
> Parsowanie zadania i nut

- .gitignore
- main/Main/Migrations/ApplicationDbContextModelSnapshot.cs
- main/Main/Pages/Browse.cshtml
- main/Main/Pages/Browse.cshtml.cs
- main/Main/Pages/Create.cshtml.cs
- main/Main/Pages/ListCreate.cshtml
- main/Main/Pages/ListCreate.cshtml.cs
- main/Main/Pages/ListJoined.cshtml
- main/Main/Pages/ListJoined.cshtml.cs
- main/Main/Pages/Solve.cshtml
- main/Main/Pages/Solve.cshtml.cs
Solve and create can now open quiz with chosen id and find users older input
> Page connecting

- .gitignore
- algorithm/Algorithm/Communication/FunctionParser.cs
- algorithm/Algorithm/Music/Symbol.cs
- creator/buttons.js
- creator/dropdowns.html
- creator/style.css
- main/Main/Components/FunctionCreator.cs
- main/Main/Main.sln
Ten etap dodaje prorotyp kreatora funkcji, na razie jako zupełnie osobna część, chwilowo niezintegrowana z resztą. Działa jednak mechanizm *pop-upów*, przygotowana jest również infrastruktura pod dalszą pracę.
Pojawiły się też niewielkie zmiany w parsowaniu funkcji, co będzie potrzebne przy kreatorze.
Dokończenie zaczętego 😉
> Prototyp kreatora funkcji - wersja alfa

- .gitignore
- algorithm/Algorithm/New/Algorithm/Mistake/FunctionMistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Mistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
- algorithm/AlgorithmTests/New/SolutionCheckerTests.cs
Ten PR skupia się na implementacji podstawowego sprawdzania błędów. Działa bez zarzutu.
<span style="color:red;"><b>Ważne!</b></span> Również w pliku .gitignore, doszły linijki, dzięki którym <u>stara wersja algorytmu nie będzie już dostępna</u>.
> Poprawki algorytmu 2 - STARY ALGORYTM ZNIKA NA ZAWSZE

- main/Main/GradingAlgorithm/GradingAlgorithm.cs
- main/Main/GradingAlgorithm/IGradingAlgorithm.cs
- main/Main/GradingAlgorithm/TestGradingAlgorithm.cs
- main/Main/Main.csproj
- main/Main/Pages/Grade.cshtml.cs
- main/Main/Program.cs
Długo wyczekiwana, integracja algorytmu z głównym projektem. Nie będę się rozpisywał, bo w sumie nie wiem jeszcze, czy działa, ponieważ na razie - ze względu na błędy, których autorem nie jestem - projektu nie da się uruchomić.
> Integracja algorytmu 1

- main/Main/Pages/Creator.cshtml
- main/Main/wwwroot/js/creator-scripts/addFunctionality.js
- main/Main/wwwroot/js/creator-scripts/component.js
- main/Main/wwwroot/js/creator-scripts/function.js
- main/Main/wwwroot/js/creator-scripts/taskCreator.js
- main/Main/wwwroot/js/creator-scripts/taskEditor.js
Był problem z ładowaniem zadania podczas edycji - konkretnie z funkcjami. Obecnie działa to jedynie w wersji podstawowej - ładują się tylko symbole oraz moll/nie moll.
- Reszta atrybutów się powinna ładować
- Tonacja i metrum powinno się faktycznie zmieniać
- Nie można dodawać pustych tasków
- Szata graficzna kreatora bardziej spójna z całością projektu
Prawdopodobnie wykonam te zadania jako kolejny pull request, może bez grafiki
> Poprawka ładowania zadań

- algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Mistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/StackMistake.cs
- algorithm/Algorithm/New/Algorithm/Parsers/NoteParser/Parser.cs
- algorithm/Algorithm/New/Algorithm/Parsers/SolutionParser/Parser.cs
- algorithm/Algorithm/New/Algorithm/Rules/DoubledFifthOnStrongBarPart.cs
- algorithm/Algorithm/New/Algorithm/Rules/OneDirection.cs
- algorithm/Algorithm/New/Algorithm/Rules/ParallelFifths.cs
- algorithm/Algorithm/New/Algorithm/Rules/ParallelOctaves.cs
- algorithm/Algorithm/New/Algorithm/Rules/Rule.cs
- algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossing.cs
- algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossingOneFunction.cs
- algorithm/Algorithm/New/Music/Stack.cs
- main/Main/Pages/Creator.cshtml
- main/Main/Pages/Solve.cshtml
- main/Main/wwwroot/js/creator-scripts/functionCreator.js
- Poprawki systemu oceniania
- Drobne poprawki kreatora
- Poprawki odporności na null'e
> Poprawki algorytmu 1

- main/Main/Pages/Groups/Details.cshtml
- main/Main/Pages/Groups/Details.cshtml.cs
- main/Main/Pages/Groups/Index.cshtml
- main/Main/Pages/Groups/Index.cshtml.cs
- main/Main/Pages/Shared/AddUsersPopup.cshtml
- main/Main/Pages/Shared/CreateGroupPopup.cshtml
- main/Main/Pages/Shared/DeleteUserPopup.cshtml
- dodanie sekcji zaproszeń
- poprawa redirectów
- poprawa uprawnień przy dodawaniu i usuwaniu: uczestnik nic nie może, master może wszystko, nauczyciel może dodać i usunąć uczestników ale nie administratorów
- poprawa onPostAddUser
- dodanie dynamicznego dodawania do listy oczekujących bez przeładowania strony
- naprawa usuwania użytkowników z grupy
- dodanie dynamicznego usuwania z listy uczestników i administratorów przy usuwaniu
> Refactor funkcjonalności group index i details

- algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Mistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/StackMistake.cs
- algorithm/Algorithm/New/Music/Function.cs
- main/Main/GradingAlgorithm/GradingAlgorithm.cs
- main/Main/GradingAlgorithm/IGradingAlgorithm.cs
- main/Main/GradingAlgorithm/TestGradingAlgorithm.cs
- main/Main/Pages/Creator.cshtml.cs
- main/Main/Pages/Grade.cshtml
- main/Main/Pages/Grade.cshtml.cs
- main/Main/Program.cs
Algorytm jest już w stanie generować opisy błędów i wstawiać je na stronę z ocenianiem.
Zmienić formę opisu z bloku tekstu, na nieco bardziej przejrzystą listę składaną - z użyciem *details* i *summary*.
> Opisy algorytmu 1

- algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
- algorithm/Algorithm/New/Algorithm/Rules/DoubledFifthOnStrongBarPart.cs
- algorithm/Algorithm/New/Algorithm/Rules/OneDirection.cs
- algorithm/Algorithm/New/Algorithm/Rules/ParallelFifths.cs
- algorithm/Algorithm/New/Algorithm/Rules/ParallelOctaves.cs
- algorithm/Algorithm/New/Algorithm/Rules/Rule.cs
- algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossing.cs
- algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossingOneFunction.cs
- algorithm/Algorithm/New/Constants.cs
- algorithm/Algorithm/New/Music/Stack.cs
- main/Main/GradingAlgorithm/GradingAlgorithm.cs
- main/Main/wwwroot/css/site.css
Listy składane generują się poprawnie. Pojawiły się również poprawki funkcjonalności algorytmu - generowanie maksymalnej liczby błędów, czy ocenianie pustych zadań.
Pojawiły się też nowe style w **site.css**, mam nadzieję, że nie mamy nigdzie indziej \<details\> i \<summary\>.
- Zgłoszone przez @mateuszejsmont - coś z tym na górze, w ekranie grade - ma być stałe, z tego co zrozumiałem.
- Wydaje mi się, że fajnie by było, żeby opinia algorytmu też miała swoje stałe miejsce na stronie, to wtedy będzie można czytać i przewijać na bieżąco, a nie że czytam nuty - przewijam - czytam błąd - przewijam...
> Opisy algorytmu 2

- main/Main/Models/ExcersiseResult.cs
- main/Main/Pages/Assigned.cshtml
- main/Main/Pages/Assigned.cshtml.cs
- main/Main/Pages/Browse.cshtml
- main/Main/Pages/Browse.cshtml.cs
- main/Main/Pages/Created.cshtml
- main/Main/Pages/Created.cshtml.cs
- main/Main/Pages/Grade.cshtml
- main/Main/Pages/Groups/Details.cshtml
- main/Main/Pages/Groups/Details.cshtml.cs
- main/Main/Pages/Shared/AddUsersPopup.cshtml
- main/Main/Pages/Shared/AssignPopup.cshtml
- main/Main/Pages/Shared/DeleteQuizPopup.cshtml
- main/Main/Pages/Shared/PublishPopup.cshtml
- main/Main/Pages/Solve.cshtml
- main/Main/Pages/Solve.cshtml.cs
- main/Main/wwwroot/css/quiz-lists-style.css
- main/Main/wwwroot/js/staff-scripts/metre.js
- main/Main/wwwroot/js/staff-scripts/sketchGrading.js
- main/Main/wwwroot/js/staff-scripts/sketchSolving.js
- main/Main/wwwroot/js/staff-scripts/staff.js
- main/Main/wwwroot/js/staff-scripts/twoNotes.js
- naprawa usuwania i publikowania quizów w Created
- refactor ekranu created: zmiana widocznych sekcji, zmiana logiki kiedy quiz jest gotowy do oceny
- naprawa dodawania quizów do grup i użytkowników
- dodanie dynamicznej zmiany przypisanych użytkowników i grup do quizu po przypisaniu
- refactor ekranu assigned: zmiana sekcji (z lewej otwarte i zaplanowane, z prawej otwarte rozwiązane i zamknięte)
- dodanie dynamicznego dodawania przycisków przy przejściu quizu w inny stan (Opened, Closed)
- refactor ekranu browse
- usuniecie brzydkiego napisu loading z rogu ekranu, teraz jest tam gdzie pięciolinia TODO można poprawić styl tego
> Poprawa logiki i wyświetlania ekranów Created i Assigned

- algorithm/Algorithm/Algorithm.csproj
- algorithm/Algorithm/New/Algorithm/Checkers/ProblemChecker.cs
- algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Problem/ProblemMistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Solution/Mistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Solution/NoteMistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Solution/StackMistake.cs
- algorithm/Algorithm/New/Algorithm/Rules/Problem/Rule.cs
- algorithm/Algorithm/New/Algorithm/Rules/Problem/SubdominantAfterDominant.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/DoubledFifthOnStrongBarPart.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/OneDirection.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelFifths.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelOctaves.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/Rule.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossing.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossingOneFunction.cs
- algorithm/Algorithm/New/Algorithm/Settings.cs
- algorithm/Algorithm/New/Algorithm/Solution.cs
- algorithm/Algorithm/New/Constants.cs
- algorithm/Algorithm/New/Music/Function.cs
- algorithm/Algorithm/New/Music/Tonation.cs
- algorithm/Algorithm/Old/Music/Interval.cs
- main/Main/GradingAlgorithm/GradingAlgorithm.cs
- main/Main/Pages/Creator.cshtml.cs
Pierwszy commit z tej gałęzi, sprawdzanie czy ktoś robi dobre zadanie również jest potrzebne.
Do zmiany jest jedynie logika funkcji **CheckResult(string question)**, w pliku *Creator.cshtml.cs* - funkcja jest okomentowana, więc nie sposób przegapić. Trzeba zrobić, żeby się nie ładowała strona ponownie, jeżeli są błędy, tylko informować o tym użytkownika.
**Obecnie, jak jest błąd, to zadanie i tak się dodaje do bazy, więc ostrożnie.**
> Walidacja kreatora 1

- main/Main/Pages/Creator.cshtml
- main/Main/Pages/Creator.cshtml.cs
- main/Main/wwwroot/js/creator-scripts/functionCreator.js
Działa. Sprawdzanie obejmuje:
- Puste zadania
- Puste funkcje w zadaniu
- Puste takty w zadaniu
- Złe następstwa funkcji (na razie tylko blokowanie dowolnego S po dowolnym D).
Walidacja odbywa się niestety jedynie na front-endzie, zmienię to potem, na razie wrzucam żeby było działające do testów.
Od teraz nie zadziałają zadania ze złymi następstwami - np. po dowolnym *D* (np. *D*, *Diii*, *Dvii*) nie może być żadnego *S* (np. *S*, *Sii*, *Svi*).
- Popup z błędami, zamiast zwykłego tekstu
Closes #82
> Walidacja kreatora zadań

- algorithm/Algorithm/New/Algorithm/Mistake/Solution/Mistake.cs
- algorithm/Algorithm/New/Algorithm/Parsers/ProblemParser/JsonProblem.cs
- algorithm/Algorithm/New/Algorithm/Parsers/ProblemParser/Parser.cs
- algorithm/Algorithm/New/Algorithm/Problem.cs
- main/Main/Data/ApplicationDbContext.cs
- main/Main/Data/ApplicationRepository.cs
- main/Main/GradingAlgorithm/GradingAlgorithm.cs
- main/Main/GradingAlgorithm/IGradingAlgorithm.cs
- main/Main/GradingAlgorithm/TestGradingAlgorithm.cs
- main/Main/Migrations/20241115104133_AddMistakeResult.Designer.cs
- main/Main/Migrations/20241115104133_AddMistakeResult.cs
- main/Main/Migrations/20241116125940_AddMistakeResults.Designer.cs
- main/Main/Migrations/20241116125940_AddMistakeResults.cs
- main/Main/Models/ExcersiseResult.cs
- main/Main/Models/ExcersiseSolution.cs
- main/Main/Models/MistakeResult.cs
- main/Main/Pages/Assigned.cshtml
- main/Main/Pages/Browse.cshtml.cs
- main/Main/Pages/Created.cshtml.cs
- main/Main/Pages/Creator.cshtml
- main/Main/Pages/Grade.cshtml
- main/Main/Pages/Grade.cshtml.cs
- main/Main/Pages/Solve.cshtml.cs
Zawarta jest w ekranie Solve, żeby ocenianie działo się po stronie użytkownika, a nie za każdym razem przy ocenianiu. Dla tego samego rozwiązania, błędy nie mają prawa się zmienić.
- Dodanie kodów błędów
- Dodanie pola z sugestią algorytmu
- Poprawa, żeby algorytm był w stanie dawać oceny za puste rozwiązania, a nie że to jest sprawdzane w 
Closes #75
> Zmiana logiki oceniania

- algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Solution/Mistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Solution/NoteMistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Solution/StackMistake.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/DoubledFifthOnStrongBarPart.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/OneDirection.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelFifths.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelOctaves.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/Rule.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossing.cs
- algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossingOneFunction.cs
- main/Main/Data/ApplicationDbContext.cs
- main/Main/Data/ApplicationRepository.cs
- main/Main/GradingAlgorithm/GradingAlgorithm.cs
- main/Main/Models/MistakeResult.cs
- main/Main/Pages/Grade.cshtml
- main/Main/Pages/Grade.cshtml.cs
- main/Main/Pages/Solve.cshtml.cs
Algorytm ponownie generuje opisy, tym razem na podstawie kodów błędów
- Brakujące głosy - napisać które
- Poprawić \<details\> - ucina takt 1
> Opisy algorytmu 3

- main/Main/Pages/Created.cshtml
- main/Main/Pages/Created.cshtml.cs
- main/Main/wwwroot/js/creator-scripts/functionContainer.js
W ekranie Created - quizy mają informowanie, co blokuje publikację. Jak bez błędów, to idzie dalej.
Closes #106
> Informowanie o błędnych quizach

- algorithm/Algorithm/New/Algorithm/Parsers/ProblemParser/Parser.cs
- algorithm/Algorithm/New/Algorithm/Parsers/SolutionParser/JsonSolution.cs
- algorithm/Algorithm/New/Algorithm/Parsers/SolutionParser/Parser.cs
- algorithm/Algorithm/New/Music/Function.cs
- algorithm/Algorithm/New/Music/Tonation.cs
- algorithm/Algorithm/New/Utils/Converters.cs
- main/Main/Migrations/20241122100312_AddBrowseAlgorithmShow.Designer.cs
- main/Main/Migrations/20241122100312_AddBrowseAlgorithmShow.cs
- main/Main/Models/QuizResult.cs
- main/Main/Pages/Assigned.cshtml
- main/Main/Pages/Browse.cshtml
- main/Main/Pages/Browse.cshtml.cs
- main/Main/Pages/Created.cshtml
- main/Main/Pages/Grade.cshtml.cs
- main/Main/Pages/Solve.cshtml.cs
- main/Main/Utils/Utils.cs
- main/Main/wwwroot/js/creator-scripts/functionCreator.js
- main/Main/wwwroot/js/staff-scripts/staff.js
- Poprawa działania zasad w algorytmie
- Dodanie możliwości uwzględnienia opinii algorytmu w ekranie browse
- Poprawa działania tonaji
- Poprawa działania moll- i nie-moll funkcji (wcześniej kropka i brak kropki w kreatorze - to kółeczko - nic nie zmieniał)
Wsm nic konkretnego, raczej implementacja dalszych zasad dla algorytmu, innych rzeczy nie przewiduję. Ewentualnie generowanie rozwiązań.
> Poprawa funkcji i UI

- algorithm/Algorithm/New/Algorithm/Generators/SolutionGenerator.cs
- algorithm/Algorithm/New/Algorithm/Parsers/SolutionParser/Parser.cs
- main/Main/Models/Excersise.cs
- main/Main/Pages/Browse.cshtml
- main/Main/Pages/Browse.cshtml.cs
Generator działa, kwestia podłączenia, żeby 2 pięciolinie działały na stronie @kubawen10
> Integracja generacji zadań

- main/Main/Models/ApplicationUser.cs
- main/Main/wwwroot/js/creator-scripts/taskContainer.js
> new creator ui

- main/Main/Migrations/20241126172429_FifthInit.Designer.cs
- main/Main/Migrations/20241126172429_FifthInit.cs
- main/Main/Pages/Creator.cshtml
- main/Main/Pages/Creator.cshtml.cs
- main/Main/Pages/Solve.cshtml
- main/Main/wwwroot/js/creator-scripts/taskContainer.js
> Dodanie labelki tonacji

- algorithm/Algorithm/New/Algorithm/Mistake/Solution/EmptyTaskMistake.cs
- algorithm/Algorithm/New/Algorithm/Mistake/Solution/Mistake.cs
- algorithm/Algorithm/New/Algorithm/Rules/Problem/AddedComponents.cs
- algorithm/Algorithm/New/Constants.cs
- main/Main/GradingAlgorithm/GradingAlgorithm.cs
- main/Main/Pages/Groups/Index.cshtml
- main/Main/Pages/Shared/_Layout.cshtml
- main/Main/Pages/Solve.cshtml.cs
- main/Main/Utils/Utils.cs
Udało się zrobić zasady sprawdzania, nie potwierdzone testami, ale z praktyki chyba działają
- Testy
- Odtwarzanie MIDI
> Zasady sprawdzania 1

- .gitignore
- algorithm/Algorithm/New/Utils/Interval.cs
- main/Main/Pages/Browse.cshtml
- main/Main/Pages/Browse.cshtml.cs
- midi/MidiPlayback/FileCreator.cs
- midi/MidiPlayback/MidiPlayback.csproj
- midi/MidiPlayback/MidiPlayback.sln
- midi/MidiPlaybackTests/FileCreateTests.cs
Implementacja odtwarzania MIDI - kompletna
- Dokumentacjaaa. Do implementacji chyba już nic nie zostało
- A nie, zapomniałem o zasadzie odległości między głosami XD - poleci jeszcze jeden PR w takim razie
> Odtwarzanie MIDI 2

- main/Main.Tests/AssignedTests.cs
- main/Main/Pages/Assigned.cshtml
- main/Main/Pages/Assigned.cshtml.cs
- main/Main/Pages/Created.cshtml
- main/Main/Pages/Creator.cshtml
- main/Main/Pages/Grade.cshtml
- main/Main/Pages/Groups/Details.cshtml
- main/Main/Pages/Groups/Index.cshtml
- main/Main/Pages/Shared/ConfirmLeavePopup.cshtml
- main/Main/Pages/Solve.cshtml
- main/Main/wwwroot/js/staff-scripts/twoNotes.js
- dodany popup potwierdzający wyjście
- przywrócony przycisk następne i zapisz w solve
- usunięte console.log
- zmiana sekcji w assigned
- zmiana tekstu przycisku ocen w created na edytuj oceny
> poprawki kilku omówionych elementów

- main/Main/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
- main/Main/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
- main/Main/Areas/Identity/Pages/Account/Login.cshtml.cs
- main/Main/Areas/Identity/Pages/Account/Register.cshtml.cs
- main/Main/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml
- main/Main/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
- main/Main/Areas/Identity/Pages/Account/ResendEmailConfirmation.cshtml.cs
- main/Main/Pages/Created.cshtml
- main/Main/Pages/Created.cshtml.cs
- main/Main/Pages/Shared/PublishPopup.cshtml
otwieranie popupu udostępnij po opublikowaniu quizu
odfiltrowanie z ocenianych quizów tych bez żadnego rozwiązania
przycisk do ponownego wysłania maila z potwierdzeniem
A i w końcu przetłumaczyłem maila z potwierdzeniem na polski
> Bs last fixes
